# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigctl < Formula
  desc ""
  homepage "https://github.com/ensigniasec/sigctl"
  version "0.2.10"

  on_macos do
    url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.10/sigctl_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "2f632469f07dbbd5cd0f03ec2033faccd4176eaa5b946877fcec3e70f2cab21c"

    def install
      bin/sigctl
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.10/sigctl_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e51caafd920b40e1dd0375549320a9f3d78dcb4467776de5d0c7db58d61455c6"

      def install
        bin/sigctl
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.10/sigctl_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a18aea8fe0f99aa1bc0aa2ee5d5b938302f85f7c4b1d73b9c38b98877a2d2599"

      def install
        bin/sigctl
      end
    end
  end
end
