# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigctl < Formula
  desc ""
  homepage "https://github.com/ensigniasec/sigctl"
  version "0.2.12"

  on_macos do
    url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.12/sigctl_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "75af43c3cef2b55e9a00021ec69b41237563d01f949007eafa1f81cb23ed1252"

    def install
      bin/sigctl
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.12/sigctl_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "623171fa7ff83e02500183fb4b10ebb35e806b2b27da8216773517e802a49392"

      def install
        bin/sigctl
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ensigniasec/sigctl/releases/download/v0.2.12/sigctl_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "398353d4c611977dfebc7e2d2a37fa7cd4e506f3c87ca995c1956baf4f91e878"

      def install
        bin/sigctl
      end
    end
  end
end
